## Automatically generated by odin - do not edit
.detSEIR <- odin:::odin_c_class("detSEIR", list(get_internal = "detSEIR_get_internal", finalise = "detSEIR_finalise", create = "detSEIR_create", initmod_desolve = "detSEIR_initmod_desolve", contents = "detSEIR_contents", set_user = "detSEIR_set_user", metadata = "detSEIR_metadata", initial_conditions = "detSEIR_initial_conditions", rhs = "detSEIR_rhs", rhs_dde = "detSEIR_rhs_dde", rhs_r = "detSEIR_rhs_r"), c("betaFX", "betaFXVal", "betaVer", "birthType", "c_Val", "c_val2", "dt", "Ef_ini", "Ej_ini", "Em_ini", "En_ini", "envOscType", "epsilon_Val", "gamma_1_Val", "gamma_2_Val", "gammaVer", "If_ini", "Ij_ini", "Im_ini", "In_ini", "kappa_Val", "m_Val", "Ma_ini", "mj_Val", "mu_Val", "omega_2_Val", "omega_m_Val", "phi_Val", "Phi2_val", "R0_Val", "Rf_ini", "rho_Val", "Rj_ini", "Rm_ini", "Rn_ini", "s_Val", "S2_val", "Sf_ini", "sigma_2_Val", "sigmaVer", "Sj_ini", "Sm_ini", "Sn_ini", "timeOscIni", "zeta_s"), list(discrete = TRUE, has_array = FALSE, has_output = FALSE, has_user = TRUE, has_delay = FALSE, has_interpolate = FALSE, has_stochastic = FALSE, has_include = FALSE, initial_time_dependent = FALSE), "batMods", "odin/detSEIR.json", TRUE)
detSEIR <- structure(function (betaFX = NULL, betaFXVal = NULL, betaVer = NULL,
    birthType = NULL, c_Val = NULL, c_val2 = NULL, dt = NULL,
    Ef_ini = NULL, Ej_ini = NULL, Em_ini = NULL, En_ini = NULL,
    envOscType = NULL, epsilon_Val = NULL, gamma_1_Val = NULL,
    gamma_2_Val = NULL, gammaVer = NULL, If_ini = NULL, Ij_ini = NULL,
    Im_ini = NULL, In_ini = NULL, kappa_Val = NULL, m_Val = NULL,
    Ma_ini = NULL, mj_Val = NULL, mu_Val = NULL, omega_2_Val = NULL,
    omega_m_Val = NULL, phi_Val = NULL, Phi2_val = NULL, R0_Val = NULL,
    Rf_ini = NULL, rho_Val = NULL, Rj_ini = NULL, Rm_ini = NULL,
    Rn_ini = NULL, s_Val = NULL, S2_val = NULL, Sf_ini = NULL,
    sigma_2_Val = NULL, sigmaVer = NULL, Sj_ini = NULL, Sm_ini = NULL,
    Sn_ini = NULL, timeOscIni = NULL, zeta_s = NULL, user = list(betaFX = betaFX,
        betaFXVal = betaFXVal, betaVer = betaVer, birthType = birthType,
        c_Val = c_Val, c_val2 = c_val2, dt = dt, Ef_ini = Ef_ini,
        Ej_ini = Ej_ini, Em_ini = Em_ini, En_ini = En_ini, envOscType = envOscType,
        epsilon_Val = epsilon_Val, gamma_1_Val = gamma_1_Val,
        gamma_2_Val = gamma_2_Val, gammaVer = gammaVer, If_ini = If_ini,
        Ij_ini = Ij_ini, Im_ini = Im_ini, In_ini = In_ini, kappa_Val = kappa_Val,
        m_Val = m_Val, Ma_ini = Ma_ini, mj_Val = mj_Val, mu_Val = mu_Val,
        omega_2_Val = omega_2_Val, omega_m_Val = omega_m_Val,
        phi_Val = phi_Val, Phi2_val = Phi2_val, R0_Val = R0_Val,
        Rf_ini = Rf_ini, rho_Val = rho_Val, Rj_ini = Rj_ini,
        Rm_ini = Rm_ini, Rn_ini = Rn_ini, s_Val = s_Val, S2_val = S2_val,
        Sf_ini = Sf_ini, sigma_2_Val = sigma_2_Val, sigmaVer = sigmaVer,
        Sj_ini = Sj_ini, Sm_ini = Sm_ini, Sn_ini = Sn_ini, timeOscIni = timeOscIni,
        zeta_s = zeta_s), unused_user_action = NULL)
{
    .detSEIR$new(user, unused_user_action)
}, ir = "odin/detSEIR.json", class = "odin_generator")
class(detSEIR) <- "odin_generator"
attr(detSEIR, "ir") <- .detSEIR$public_fields$ir
.stochSEIR <- odin:::odin_c_class("stochSEIR", list(get_internal = "stochSEIR_get_internal", finalise = "stochSEIR_finalise", create = "stochSEIR_create", initmod_desolve = "stochSEIR_initmod_desolve", contents = "stochSEIR_contents", set_user = "stochSEIR_set_user", metadata = "stochSEIR_metadata", initial_conditions = "stochSEIR_initial_conditions", rhs = "stochSEIR_rhs", rhs_dde = "stochSEIR_rhs_dde", rhs_r = "stochSEIR_rhs_r"), c("betaFX", "betaFXVal", "betaVer", "birthType", "c_Val", "c_val2", "dt", "Ef_ini", "Ej_ini", "Em_ini", "En_ini", "envOscType", "epsilon_Val", "gamma_1_Val", "gamma_2_Val", "gammaVer", "If_ini", "Ij_ini", "Im_ini", "In_ini", "kappa_Val", "m_Val", "Ma_ini", "mj_Val", "mu_Val", "omega_2_Val", "omega_m_Val", "phi_Val", "Phi2_val", "R0_Val", "Rf_ini", "rho_Val", "Rj_ini", "Rm_ini", "Rn_ini", "s_Val", "S2_val", "Sf_ini", "sigma_2_Val", "sigmaVer", "Sj_ini", "Sm_ini", "Sn_ini", "timeOscIni", "zeta_s"), list(discrete = TRUE, has_array = TRUE, has_output = FALSE, has_user = TRUE, has_delay = FALSE, has_interpolate = FALSE, has_stochastic = TRUE, has_include = FALSE, initial_time_dependent = FALSE), "batMods", "odin/stochSEIR.json", TRUE)
stochSEIR <- structure(function (betaFX = NULL, betaFXVal = NULL, betaVer = NULL,
    birthType = NULL, c_Val = NULL, c_val2 = NULL, dt = NULL,
    Ef_ini = NULL, Ej_ini = NULL, Em_ini = NULL, En_ini = NULL,
    envOscType = NULL, epsilon_Val = NULL, gamma_1_Val = NULL,
    gamma_2_Val = NULL, gammaVer = NULL, If_ini = NULL, Ij_ini = NULL,
    Im_ini = NULL, In_ini = NULL, kappa_Val = NULL, m_Val = NULL,
    Ma_ini = NULL, mj_Val = NULL, mu_Val = NULL, omega_2_Val = NULL,
    omega_m_Val = NULL, phi_Val = NULL, Phi2_val = NULL, R0_Val = NULL,
    Rf_ini = NULL, rho_Val = NULL, Rj_ini = NULL, Rm_ini = NULL,
    Rn_ini = NULL, s_Val = NULL, S2_val = NULL, Sf_ini = NULL,
    sigma_2_Val = NULL, sigmaVer = NULL, Sj_ini = NULL, Sm_ini = NULL,
    Sn_ini = NULL, timeOscIni = NULL, zeta_s = NULL, user = list(betaFX = betaFX,
        betaFXVal = betaFXVal, betaVer = betaVer, birthType = birthType,
        c_Val = c_Val, c_val2 = c_val2, dt = dt, Ef_ini = Ef_ini,
        Ej_ini = Ej_ini, Em_ini = Em_ini, En_ini = En_ini, envOscType = envOscType,
        epsilon_Val = epsilon_Val, gamma_1_Val = gamma_1_Val,
        gamma_2_Val = gamma_2_Val, gammaVer = gammaVer, If_ini = If_ini,
        Ij_ini = Ij_ini, Im_ini = Im_ini, In_ini = In_ini, kappa_Val = kappa_Val,
        m_Val = m_Val, Ma_ini = Ma_ini, mj_Val = mj_Val, mu_Val = mu_Val,
        omega_2_Val = omega_2_Val, omega_m_Val = omega_m_Val,
        phi_Val = phi_Val, Phi2_val = Phi2_val, R0_Val = R0_Val,
        Rf_ini = Rf_ini, rho_Val = rho_Val, Rj_ini = Rj_ini,
        Rm_ini = Rm_ini, Rn_ini = Rn_ini, s_Val = s_Val, S2_val = S2_val,
        Sf_ini = Sf_ini, sigma_2_Val = sigma_2_Val, sigmaVer = sigmaVer,
        Sj_ini = Sj_ini, Sm_ini = Sm_ini, Sn_ini = Sn_ini, timeOscIni = timeOscIni,
        zeta_s = zeta_s), unused_user_action = NULL)
{
    .stochSEIR$new(user, unused_user_action)
}, ir = "odin/stochSEIR.json", class = "odin_generator")
class(stochSEIR) <- "odin_generator"
attr(stochSEIR, "ir") <- .stochSEIR$public_fields$ir
.stochSEIRadInf <- odin:::odin_c_class("stochSEIRadInf", list(get_internal = "stochSEIRadInf_get_internal", finalise = "stochSEIRadInf_finalise", create = "stochSEIRadInf_create", initmod_desolve = "stochSEIRadInf_initmod_desolve", contents = "stochSEIRadInf_contents", set_user = "stochSEIRadInf_set_user", metadata = "stochSEIRadInf_metadata", initial_conditions = "stochSEIRadInf_initial_conditions", rhs = "stochSEIRadInf_rhs", rhs_dde = "stochSEIRadInf_rhs_dde", rhs_r = "stochSEIRadInf_rhs_r"), c("betaVer", "c_Val", "dt", "Ef_ini", "Ej_ini", "Em_ini", "En_ini", "epsilon_Val", "gamma_1_Val", "gamma_2_Val", "gammaVer", "If_ini", "Im_ini", "kappa_Val", "m_Val", "Ma_ini", "mj_Val", "mu_Val", "omega_2_Val", "omega_m_Val", "phi_Val", "R0_Val", "Rf_ini", "rho_Val", "Rj_ini", "Rm_ini", "Rn_ini", "s_Val", "Sf_ini", "sigma_1_Val", "sigma_2_Val", "sigmaVer", "Sj_ini", "Sm_ini", "Sn_ini"), list(discrete = TRUE, has_array = TRUE, has_output = FALSE, has_user = TRUE, has_delay = FALSE, has_interpolate = FALSE, has_stochastic = TRUE, has_include = FALSE, initial_time_dependent = FALSE), "batMods", "odin/stochSEIRadInf.json", TRUE)
stochSEIRadInf <- structure(function (betaVer = NULL, c_Val = NULL, dt = NULL,
    Ef_ini = NULL, Ej_ini = NULL, Em_ini = NULL, En_ini = NULL,
    epsilon_Val = NULL, gamma_1_Val = NULL, gamma_2_Val = NULL,
    gammaVer = NULL, If_ini = NULL, Im_ini = NULL, kappa_Val = NULL,
    m_Val = NULL, Ma_ini = NULL, mj_Val = NULL, mu_Val = NULL,
    omega_2_Val = NULL, omega_m_Val = NULL, phi_Val = NULL, R0_Val = NULL,
    Rf_ini = NULL, rho_Val = NULL, Rj_ini = NULL, Rm_ini = NULL,
    Rn_ini = NULL, s_Val = NULL, Sf_ini = NULL, sigma_1_Val = NULL,
    sigma_2_Val = NULL, sigmaVer = NULL, Sj_ini = NULL, Sm_ini = NULL,
    Sn_ini = NULL, user = list(betaVer = betaVer, c_Val = c_Val,
        dt = dt, Ef_ini = Ef_ini, Ej_ini = Ej_ini, Em_ini = Em_ini,
        En_ini = En_ini, epsilon_Val = epsilon_Val, gamma_1_Val = gamma_1_Val,
        gamma_2_Val = gamma_2_Val, gammaVer = gammaVer, If_ini = If_ini,
        Im_ini = Im_ini, kappa_Val = kappa_Val, m_Val = m_Val,
        Ma_ini = Ma_ini, mj_Val = mj_Val, mu_Val = mu_Val, omega_2_Val = omega_2_Val,
        omega_m_Val = omega_m_Val, phi_Val = phi_Val, R0_Val = R0_Val,
        Rf_ini = Rf_ini, rho_Val = rho_Val, Rj_ini = Rj_ini,
        Rm_ini = Rm_ini, Rn_ini = Rn_ini, s_Val = s_Val, Sf_ini = Sf_ini,
        sigma_1_Val = sigma_1_Val, sigma_2_Val = sigma_2_Val,
        sigmaVer = sigmaVer, Sj_ini = Sj_ini, Sm_ini = Sm_ini,
        Sn_ini = Sn_ini), unused_user_action = NULL)
{
    .stochSEIRadInf$new(user, unused_user_action)
}, ir = "odin/stochSEIRadInf.json", class = "odin_generator")
class(stochSEIRadInf) <- "odin_generator"
attr(stochSEIRadInf, "ir") <- .stochSEIRadInf$public_fields$ir
